package com.example.model

/**
 * Daily Market Sentiment Summary generated by Gemini using Firebase GenAI SDK
 */
data class GeminiDailyOutlook(
    val sentiment: MarketSentimentType = MarketSentimentType.MODERATE_BULLISH,
    val confidencePercentage: Int = 82,
    val executiveSummary: String = "",
    val planetaryCatalysts: List<PlanetaryCatalyst> = emptyList(),
    val sectorRankings: List<SectorSentimentOutlook> = emptyList(),
    val tradingWindows: List<AstroTradingWindow> = emptyList(),
    val actionableStrategy: String = "",
    val astrologicalContextSnapshot: String = "",
    val generatedAtTimestamp: Long = System.currentTimeMillis(),
    val modelTag: String = "gemini-2.5-flash (Firebase GenAI SDK)"
)

enum class MarketSentimentType(
    val label: String,
    val badgeColorHex: Long,
    val iconName: String
) {
    BULLISH("Bullish Surge", 0xFF10B981, "trending_up"),
    MODERATE_BULLISH("Cautiously Bullish / Buy Dips", 0xFF34D399, "trending_up"),
    NEUTRAL_CONSOLIDATING("Rangebound / Consolidating", 0xFF94A3B8, "swap_horiz"),
    BEARISH("Bearish Drag / Selling Pressure", 0xFFEF4444, "trending_down"),
    VOLATILE_CAUTION("High Volatility / Whipsaw Alert", 0xFFF97316, "warning")
}

data class PlanetaryCatalyst(
    val planetName: String,
    val symbol: String,
    val role: String,
    val impactAnalysis: String,
    val sentimentBias: String // "Bullish", "Defensive", "Volatile"
)

data class SectorSentimentOutlook(
    val sectorName: String,
    val stance: String, // "Favored / Accumulate", "Neutral / Hold", "Under Pressure / Hedge"
    val planetaryDriver: String,
    val guidance: String
)

data class AstroTradingWindow(
    val windowName: String,
    val timeRange: String,
    val expectedImpact: String,
    val isCaution: Boolean = false
)

sealed interface GeminiOutlookUiState {
    data object Idle : GeminiOutlookUiState
    data object Loading : GeminiOutlookUiState
    data class Success(val outlook: GeminiDailyOutlook) : GeminiOutlookUiState
    data class Error(val message: String, val fallbackOutlook: GeminiDailyOutlook? = null) : GeminiOutlookUiState
}
